---
name: "PNPM Init Action"
description: "Initialize PNPM"
runs:
  using: "composite"
  steps:
    - name: 🆙 Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: 🆙 Setup pnpm config
      shell: bash
      run: pnpm config set store-dir .pnpm-store

    - name: ⏬ Install pnpm
      shell: bash
      run: pnpm install
