---
name: Publish

on:
  workflow_call:

jobs:
  validate:
    name: Publish
    runs-on: ubuntu-24.04 # Use Ubuntu 24.04 explicitly
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v4

      - name: 🔄 Init PNPM
        uses: ./.github/actions/pnpm-init

      - name: ⏬ Download dist
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: 🔀 Extract tag
        shell: bash
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: extractTag

      - name: 🔜 Publish to npm
        env:
          TAG: ${{ steps.extractTag.outputs.tag }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          SEMVER_VERSION=$(npx find-versions-cli "$TAG")
          npm version --no-git-tag-version "$SEMVER_VERSION"
          npm config set registry https://registry.npmjs.org/
          npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
          npm publish --provenance
