name: Default Pipeline

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  init:
    uses: ./.github/workflows/00-init.yml

  fonttools-test:
    uses: ./.github/workflows/00-fonttools-test.yml

  scan-secrets:
    # disable secret scanning on "main" branch (because truffleHog has issues with this) and check for a fork as the source that's heading on the main branch, which would fail as well.
    if: github.event.pull_request == null || github.event.pull_request.head.repo.owner.login == 'db-ui'
    uses: ./.github/workflows/00-scan-secrets.yml

  build:
    uses: ./.github/workflows/01-build.yml
    needs: [init]
    secrets: inherit

  lint:
    uses: ./.github/workflows/01-lint.yml
    needs: [init]
    secrets: inherit

  test:
    uses: ./.github/workflows/01-test.yml
    needs: [init]
    secrets: inherit
